export const CUSTOMER_LIST_HAVE_ERROR = 'CUSTOMER_LIST_HAVE_ERROR';
export const CUSTOMER_LIST_ARE_LOADING = 'CUSTOMER_LIST_ARE_LOADING';
export const CUSTOMER_LIST_FETCH_DATA_SUCCESS = 'CUSTOMER_LIST_FETCH_DATA_SUCCESS';
