export const PRODUCT_LIST_HAVE_ERROR = 'PRODUCT_LIST_HAVE_ERROR';
export const PRODUCT_LIST_ARE_LOADING = 'PRODUCT_LIST_ARE_LOADING';
export const PRODUCT_LIST_FETCH_DATA_SUCCESS = 'PRODUCT_LIST_FETCH_DATA_SUCCESS';
