export const QUOTE_LIST_HAVE_ERROR = 'QUOTE_LIST_HAVE_ERROR';
export const QUOTE_LIST_ARE_LOADING = 'QUOTE_LIST_ARE_LOADING';
export const QUOTE_LIST_FETCH_DATA_SUCCESS = 'QUOTE_LIST_FETCH_DATA_SUCCESS';
