export const USER_LIST_HAVE_ERROR = 'USER_LIST_HAVE_ERROR';
export const USER_LIST_ARE_LOADING = 'USER_LIST_ARE_LOADING';
export const USER_LIST_FETCH_DATA_SUCCESS = 'USER_LIST_FETCH_DATA_SUCCESS';
export const USER_CLEAR_CREDENTIALS = 'USER_CLEAR_CREDENTIALS';